export const LOCATIONS = [
  "Almadies 2 Dakar", "Almadies Dakar", "Amitié Dakar", "Avenue Bourguiba Dakar",
  "Bambilor Dakar", "Bargny Dakar", "Bayakh Dakar", "Bel air Dakar",
  "Cambérène Dakar", "Castor Dakar", "Cite Mixta Dakar", "Cité Damel Dakar",
  "Cité assemblée Dakar", "Cité avion Dakar", "Cité biagui Dakar",
  "Cité keur gorgui Dakar", "Colobane Dakar", "Corniche Dakar",
  "Dakar", "Dakar Dakar", "Dalifort Dakar", "Derkle Dakar",
  "Diamniadio Dakar", "Diamaguene Dakar", "Dieuppeul Dakar",
  "Djily mbaye Dakar", "Fann Dakar", "Fann Hock Dakar", "Fass Dakar",
  "Fenêtre mermoz Dakar", "Golf Dakar", "Gorée Dakar", "Gorom Dakar",
  "Grand-Dakar Dakar", "Grand-Yoff Dakar", "Guediawaye Dakar",
  "HLM Grand Médine Dakar", "Hann Bel-Air Dakar", "Hann marinas Dakar",
  "Hann maristes Dakar", "Hlm Dakar", "Hlm grand-yoff Dakar",
  "Karack Dakar", "Keur Massar Dakar", "Keur ndiaye lô Dakar",
  "Kounoune Dakar", "Lac Rose Dakar", "Lac rose Dakar",
  "Liberte 1 Dakar", "Liberte 2 Dakar", "Liberte 3 Dakar",
  "Liberte 4 Dakar", "Liberte 5 Dakar", "Liberte 6 Dakar",
  "Liberte 6 extension Dakar", "Malika Dakar", "Mamelles Dakar",
  "Mbao Dakar", "Mermoz Dakar", "Médina Dakar",
  "Ndiakhirate Dakar", "Ngor Dakar", "Niague Dakar",
  "Niakoul rap Dakar", "Noflaye Dakar", "Nord foire Dakar",
  "Ouakam Dakar", "Ouest foire Dakar", "Parcelles Assainies Dakar",
  "Patte d'oie Dakar", "Pikine Dakar", "Plateau Dakar", "Point-e Dakar",
  "Rufisque Dakar", "Sacré-cœur Dakar", "Sangalkam Dakar",
  "Sebikotane Dakar", "Sendou Dakar", "Sicap Liberté Dakar",
  "Sicap Sacré-cœur Dakar", "Sicap baobab Dakar", "Sicap foire Dakar",
  "Sicap mbao Dakar", "Sud foire Dakar", "Thiaroye Dakar",
  "Thongor Dakar", "Tivaouane peulh Dakar", "Toubab dialo Dakar",
  "VDN Dakar", "Virage Dakar", "Yene Dakar", "Yeumbeul Dakar",
  "Yoff Dakar", "Zac Mbao Dakar", "Zone de captage Dakar",
  "Zone industrielle Dakar", "cité magistrat Dakar", "scat urbam Dakar",
  "vdn 3 Dakar",
] as const;
